In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

In [2]:
file_name = "../dataset/ecommerce_cleaned.csv"
df = pd.read_csv(file_name)

df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,...,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender,order_month,order_year,order_day_of_week,age_group
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,...,0,139.47,7.88,31.17,60,1,12,2023,5,Middle
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,...,0,24.73,4.60,-2.62,37,0,4,2025,3,Adult
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,...,0,166.80,6.58,13.44,34,0,10,2024,1,Adult
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,...,0,63.67,5.50,2.14,21,1,9,2024,5,Young
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,...,0,13.88,2.74,1.15,39,0,12,2024,5,Adult

In [3]:
gender_map = {
    "Male": 0,
    "Female": 1,
    "Other": 2
}

df["customer_gender"] = df["customer_gender"].map(gender_map)

df.head(20)

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,...,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender,order_month,order_year,order_day_of_week,age_group
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,...,0,139.47,7.88,31.17,60,NaN,12,2023,5,Middle
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,...,0,24.73,4.60,-2.62,37,NaN,4,2025,3,Adult
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,...,0,166.80,6.58,13.44,34,NaN,10,2024,1,Adult
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,...,0,63.67,5.50,2.14,21,NaN,9,2024,5,Young
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,...,0,13.88,2.74,1.15,39,NaN,12,2024,5,Adult
5,O100005,C15191,P214062,Beauty,53.91,0.10,2,Credit Card,2024-04-14,5,...,0,97.04,6.32,37.35,35,NaN,4,2024,6,Adult
6,O100006,C13772,P201363,Electronics,266.50,0.00,1,PayPal,2025-05-20,5,...,0,266.50,9.10,22.88,49,NaN,5,2025,1,Middle
7,O100007,C13092,P216691,Beauty,9.98,0.00,1,Credit Card,2023-09-14,4,...,0,9.98,4.51,-0.02,66,NaN,9,2023,3,Senior
8,O100008,C15734,P202751,Fashion,6.61,0.05,1,Debit Card,2023-10-23,6,...,0,6.28,3.43,-1.23,37,NaN,10,2023,0,Adult
9,O100009,C16265,P207782,Grocery,10.91,0.00,1,Credit Card,2023-10-31,6,...,0,10.91,2.76,-1.89,56,NaN,10,2023,1,Middle
10,O100010,C10466,P217648,Beauty,6.61,0.10,1,Debit Card,2024-02-07,5,...,0,5.95,2.16,0.52,40,NaN,2,2024,2,Adult
11,O100011,C15334,P212540,Beauty,16.22,0.00,1,PayPal,2024-07-08,5,...,0,16.22,3.72,3.58,21,NaN,7,2024,0,Young
12,O100012,C14426,P245991,Grocery,10.56,0.10,1,Credit Card,2024-10-13,4,...,0,9.50,4.99,-4.23,22,NaN,10,2024,6,Young
13,O100013,C15578,P205339,Toys,7.12,0.00,1,Debit Card,2023-11-01,5,...,0,7.12,3.35,-0.50,56,NaN,11,2023,2,Middle
14,O100014,C16231,P227020,Home,39.19,0.00,2,Credit Card,2025-02-24,3,...,0,78.38,7.91,14.04,63,NaN,2,2025,0,Senior
15,O100015,C13444,P227609,Home,12.63,0.20,4,Credit Card,2024-05-03,3,...,0,40.42,6.19,5.13,36,NaN,5,2024,4,Adult
16,O100016,C13171,P205848,Sports,96.61,0.05,1,PayPal,2024-08-25,4,...,0,91.78,3.60,23.93,47,NaN,8,2024,6,Middle
17,O100017,C12919,P216877,Fashion,16.00,0.00,3,PayPal,2024-09-12,5,...,0,48.00,4.48,12.32,37,NaN,9,2024,3,Adult
18,O100018,C17831,P218405,Electronics,734.32,0.00,2,Wallet,2025-06-20,4,...,0,1468.64,10.90,165.34,58,NaN,6,2025,4,Middle
19,O100019,C10130,P248629,Fashion,50.52,0.00,1,Credit Card,2024-10-10,3,...,1,50.52,6.20,11.48,56,NaN,10,2024,3,Middle

In [4]:

df.isnull().sum()

order_id              0
customer_id           0
product_id            0
category              0
price                 0
discount              0
quantity              0
payment_method        0
order_date            0
delivery_time_days    0
region                0
returned              0
total_amount          0
shipping_cost         0
profit_margin         0
customer_age          0
customer_gender       0
dtype: int64

In [5]:
return_map = {
    "Yes": 1,
    "No": 0
}
df["returned"] = df["returned"].map(return_map)
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,West,0,139.47,7.88,31.17,60,1
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,South,0,24.73,4.60,-2.62,37,0
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,North,0,166.80,6.58,13.44,34,0
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,South,0,63.67,5.50,2.14,21,1
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,East,0,13.88,2.74,1.15,39,0

In [6]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["order_month"] = df["order_date"].dt.month
df["order_year"] = df["order_date"].dt.year

df["order_day_of_week"] = df["order_date"].dt.dayofweek
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,region,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender,order_month,order_year,order_day_of_week
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,West,0,139.47,7.88,31.17,60,1,12,2023,5
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,South,0,24.73,4.60,-2.62,37,0,4,2025,3
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,North,0,166.80,6.58,13.44,34,0,10,2024,1
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,South,0,63.67,5.50,2.14,21,1,9,2024,5
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,East,0,13.88,2.74,1.15,39,0,12,2024,5

In [7]:
print("total_unique_rows",len(df))
print("total_number_of_customer_id",len(df["customer_id"].unique()))
print("total_number_of_order_id",len(df["order_id"].unique()))

total_unique_rows 34500
total_number_of_customer_id 7903
total_number_of_order_id 34500

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 34500 entries, 0 to 34499
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            34500 non-null  str
 1   customer_id         34500 non-null  str
 2   product_id          34500 non-null  str
 3   category            34500 non-null  str
 4   price               34500 non-null  float64
 5   discount            34500 non-null  float64
 6   quantity            34500 non-null  int64
 7   payment_method      34500 non-null  str
 8   order_date          34500 non-null  datetime64[us]
 9   delivery_time_days  34500 non-null  int64
 10  region              34500 non-null  str
 11  returned            34500 non-null  int64
 12  total_amount        34500 non-null  float64
 13  shipping_cost       34500 non-null  float64
 14  profit_margin       34500 non-null  float64
 15  customer_age        34500 non-null  int64
 16  customer_gender     34500 non-null  int64
 17  order_month         34500 non-null  int32
 18  order_year          34500 non-null  int32
 19  order_day_of_week   34500 non-null  int32
dtypes: datetime64[us](1), float64(5), int32(3), int64(5), str(6)
memory usage: 4.9 MB

In [9]:
df["age_group"] = pd.cut(
    df["customer_age"],
    bins=[0, 25, 40, 60, 100],
    labels=["Young", "Adult", "Middle", "Senior"]
)
df.head()

,order_id,customer_id,product_id,category,price,discount,quantity,payment_method,order_date,delivery_time_days,...,returned,total_amount,shipping_cost,profit_margin,customer_age,customer_gender,order_month,order_year,order_day_of_week,age_group
0,O100000,C17270,P234890,Home,164.08,0.15,1,Credit Card,2023-12-23,4,...,0,139.47,7.88,31.17,60,1,12,2023,5,Middle
1,O100001,C17603,P228204,Grocery,24.73,0.00,1,Credit Card,2025-04-03,6,...,0,24.73,4.60,-2.62,37,0,4,2025,3,Adult
2,O100002,C10860,P213892,Electronics,175.58,0.05,1,Credit Card,2024-10-08,4,...,0,166.80,6.58,13.44,34,0,10,2024,1,Adult
3,O100003,C15390,P208689,Electronics,63.67,0.00,1,UPI,2024-09-14,6,...,0,63.67,5.50,2.14,21,1,9,2024,5,Young
4,O100004,C15226,P228063,Home,16.33,0.15,1,COD,2024-12-21,6,...,0,13.88,2.74,1.15,39,0,12,2024,5,Adult

In [10]:
df.to_csv("./dataset/ecommerce_cleaned.csv", index=False)
print("Saved!")

Saved!